# Generated by Django 2.2.2 on 2019-06-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(blank=True, max_length=100, null=True, verbose_name='term')),
                ('meaning', models.TextField(blank=True, null=True, verbose_name='meaning of the term')),
            ],
        ),
    ]
