# Generated by Django 2.2.1 on 2019-07-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientNumber', models.IntegerField(blank=True, null=True, verbose_name='Patient No. as appears on "superspreadsheet.csv"')),
                ('firstName', models.CharField(blank=True, max_length=15, null=True, verbose_name='first name')),
                ('lastName', models.CharField(blank=True, max_length=15, null=True, verbose_name='last name')),
                ('admitAge', models.IntegerField(blank=True, null=True, verbose_name='age of patient when admitted')),
                ('admitYear', models.IntegerField(blank=True, null=True, verbose_name='year patient was admitted')),
                ('admitMonth', models.IntegerField(blank=True, null=True, verbose_name='month patient was admitted')),
                ('admitDate', models.IntegerField(blank=True, null=True, verbose_name='date patient was admitted')),
                ('admitDateFull', models.CharField(blank=True, max_length=15, null=True, verbose_name='month/date/year patient was admitted')),
                ('leaveDateFull', models.CharField(blank=True, max_length=15, null=True, verbose_name='date patient was discharged')),
            ],
        ),
    ]
