# Generated by Django 2.2.1 on 2019-07-22 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qmh', '0002_patientinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientInfo',
            new_name='Patient',
        ),
    ]
