# Generated by Django 2.2.1 on 2019-07-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmh', '0003_auto_20190722_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='admitDate',
        ),
        migrations.AlterField(
            model_name='patient',
            name='admitDateFull',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='month/day/year patient was admitted'),
        ),
    ]
