# Generated by Django 2.2.1 on 2019-07-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmh', '0004_auto_20190722_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='gender'),
        ),
    ]
