# Generated by Django 2.2.1 on 2019-07-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmh', '0005_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='admitMonth',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='month patient was admitted'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='admitYear',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='year patient was admitted'),
        ),
    ]
