# Generated by Django 2.2.1 on 2019-07-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmh', '0006_auto_20190722_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patientNumber',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Patient No. as appears on "superspreadsheet.csv"'),
        ),
    ]
