# Generated by Django 2.2.1 on 2019-07-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmh', '0007_auto_20190722_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patientNumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='Patient No. as appears on "superspreadsheet.csv"'),
        ),
    ]
